import type { Metadata } from "next";
// import { Geist } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "pullup-counter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`
 w-full h-full 
 `}
    >
      <body className="min-h-full min-w-full flex flex-col bg-neutral-50 text-neutral-950">
        {children}
      </body>
    </html>
  );
}
